version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userdb
    networks:
      - dev-network
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    restart: always

  rabbitmq:
    image: 'bitnami/rabbitmq:3.9.14'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: userpass
    networks:
      - dev-network
    ports:
      - '5672:5672'
      - '15672:15672'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    command: ["go", "run", "cmd/server/main.go"]
    restart: always
    networks:
      - dev-network
    depends_on:
      - rabbitmq
      - postgres

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "cmd/consumer/main.go"]
    restart: always
    networks:
      - dev-network
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres-data:

networks:
  dev-network:
    driver: bridge